export const LOCAL_IMAGES = {
  splash: require('../assets/images/welcome.png'),
  backGroundImg: require('../assets/images/header-bg.png'),
  orderImg: require('../assets/images/order.png'),
  paymentImg: require('../assets/images/Payment.png'),
  rightIcon: require('../assets/images/Vector.png'),
  locationIcon: require('../assets/images/Vector.png'),
  groupIcon: require('../assets/images/Group.png'),
  homeIcon: require('../assets/images/home.png'),
  searchIcon: require('../assets/images/search.png'),
  profileIcon: require('../assets/images/profile.png'),
  womenIcon: require('../assets/images/avtar.png'),
  editIcon: require('../assets/images/edit.png'),
  dropDownIcon: require('../assets/images/dropdownIcon.png'),
  foodIcon: require('../assets/images/img.png'),
  vegetableIcon: require('../assets/images/foodIcon.png'),
  rotationIcon: require('../assets/images/rotationlock.png'),
};
